### ISSUE TITLE
Copy docs to wiki for simplified 3rd party development

### ISSUE THREAD

**Issue by Unit158** [ZeroKelvinKeyboard/TachyonOS#1]
The documentation would be much easier to read and navigate in a proper rich text environment such as Github's wiki.

**Comment by ZeroKelvinKeyboard** [comment]
I'll see what can I can do. At the moment there's the documentation of API calls inherited from MikeOS in a pretty HTML file and newer calls that I've added in a less pretty plain text document. I would like to do one of the following:
(A) Extend MikeOS HTML documentation to include all the API calls TachyonOS adds. Would probably take a while but the result will look nice if not a little unoriginal.
(B) Convert everything to some kind of wiki format (like markdown). Much easier than the first option but much less powerful.
(C) Put everything into comment blocks and use a documentation generator. This would be a good idea to avoid having code and docs as two separate parts but it's probably going to take too long if not done from the start.

**Comment by ZeroKelvinKeyboard** [comment]
I've started a wiki if you are interested. I've decided to use Markdown as my Wiki format. Markdown seems to lack power but it's workable. I'd like to convert it to HTML with the offline files so that it is actually readable.
