### ISSUE TITLE
If I try to launch any BIN or BAS through the File Manager (BlackSVK), TachyonOS freezes with blinking cursor at the top left corner of black screen

### ISSUE THREAD

**Issue by informer2016** [ZeroKelvinKeyboard/TachyonOS#10]
Observed at both coreboot+SeaBIOS and QEMU, can't test on VirtualBox because of blocking problem #9 . Files with the other extensions - SND, AAP, MAP, PRG, TXT, SYS - just don't run and nothing happens when I press the "Enter" key

**Comment by ZeroKelvinKeyboard** [comment]
BlackSVK does a lot of strange things and I can't find the source code, so I'm not really sure what the problem is here. Never the less, I'll look into it.
