### ISSUE TITLE
Y mouse axis seems to be not working, but follows X as " X/2 "

### ISSUE THREAD

**Issue by informer2016** [ZeroKelvinKeyboard/TachyonOS#11]
@ZeroKelvinKeyboard , I tried DREW2.BAS and could not escape out of this line, image attached _(erased the black background because my screen is really glossy)_ Only X axis seems to work, and MOUSE.BIN app always gives me Y = X/2 - this Y axis basically follows X, e.g. Mouse X: 41 then Mouse Y: 20 . Debug information from MOUSE.BIN: **0101A.700A7.00290.01400.02030.00000.003C0.1C000.00000.000**
Both mouse buttons are working, and X axis is working too, only the Y axis is problematic. This problem observed with many mouse apps, so there seems to be a problem with mouse driver
![mouse](https://user-images.githubusercontent.com/26509528/49964177-e9bd3280-ff2a-11e8-9d69-22196343d5ae.png)

**Comment by ZeroKelvinKeyboard** [comment]
The mouse driver is full of terrible code that's not likely to work on many machines and can in some cases lock up the machine entirely. I'm planning on removing it, at least until it can be replaced with more sensible code.
