### ISSUE TITLE
Outdated apps! e.g. MikeOS 4.5 has CF.BAS version 2.0.2, but Tachyon's CF.BAS is older 2.0

### ISSUE THREAD

**Issue by informer2016** [ZeroKelvinKeyboard/TachyonOS#12]
I fully support ticket #6 - "**_Update to use MikeOS v4.6b2 (as the base)"_** . Or at least use v4.5 as the base, still better than some even older version of MikeOS

**Comment by informer2016** [comment]
@ZeroKelvinKeyboard Good day ZKelvin! Any news about TachyonOS ? ;) btw I wrote many issues there :)

**Comment by ZeroKelvinKeyboard** [comment]
It's not really clear what updating the base MikeOS version would mean, but I'll look into updating the apps.

**Comment by ZeroKelvinKeyboard** [comment]
The program has been updated.

**Comment by informer2016** [comment]
@ZeroKelvinKeyboard By "updating the base MikeOS version" I meant that after you forked MikeOS into TachyonOS there were some additional commits to MikeOS which improved it, but they haven't made it into TachyonOS - like this CF.BAS 2.0 -> 2.0.2 upgrade . Sadly I'm a neck deep in coreboot stuff at the moment so can't track down all the differences to create a nice pull request, at least yet...

**Comment by ZeroKelvinKeyboard** [comment]
Given the internal differences now, it's going to be "porting over" not "updating the base MikeOS version". I'll have a look but I'm not sure whether there's anything worth porting over. Most of the changes were features that already existed in TachyonOS and fixes for bugs that only existed in MikeOS.
