### ISSUE TITLE
There is a problem with All Programs Menu...

### ISSUE THREAD

**Issue by Htroisc** [ZeroKelvinKeyboard/TachyonOS#5]
Hello ! I am Htroisc and I tested your Operating System : Tachyon OS. Tachyon OS is a good operating system with a lof of work. But, there are some bugs, including a critical... It happens when I try to open the All Programs Menu. The Green Window become black and the screen displays : AX:1000, BX:0000,CX:0. I really hope that I have been helpful to you. Good Night !

P.S : Sorry for bad English, I'm french...

**Comment by ZeroKelvinKeyboard** [comment]
Fixed in build #12 of TachyonOS.
