### ISSUE TITLE
[coreboot+SeaBIOS, or QEMU] Checking for autorun binary...... FAILED while booting (everything else is SUCCESS and booting is successful)

### ISSUE THREAD

**Issue by informer2016** [ZeroKelvinKeyboard/TachyonOS#8]
Problem observed while booting TachyonOS as a virtual floppy from coreboot+SeaBIOS ( for more information see https://github.com/ZeroKelvinKeyboard/TachyonOS/issues/4 ) . Booting is successful and it is unclear how this error affects the functionality of TachyonOS

**Comment by ZeroKelvinKeyboard** [comment]
This is a non-issue.

The message you quoted occurs when the file 'AUTORUN.BIN' does not exist. This file is an optional binary file that can be run at boot time.
